### ISSUE TITLE
n_frames, n_videos... are Zero

### ISSUE THREAD

**Issue by divided7** [lyhisme/DeST#2]
code in Colab: https://colab.research.google.com/drive/1ulutg5YMGRKLf86b4ylHlmraBj69gHEo?usp=sharing

Traceback (most recent call last):
  File "/content/DeST/train.py", line 381, in <module>
    main()
  File "/content/DeST/train.py", line 273, in main
    ) = validate(
  File "/content/DeST/libs/helper.py", line 142, in validate
    cls_acc, edit_score, segment_f1s = scores_after_refinement.get_scores()
  File "/content/DeST/libs/metric.py", line 233, in get_scores
    acc = 100 * float(self.n_correct) / self.n_frames
ZeroDivisionError: float division by zero

**Comment by wtnan2003** [comment]
The file csv/MCFS-130/val1.csv is empty, which is causing the issue. I fixed it by copying the contents of text2.csv into val1.csv
[val1.csv](https://github.com/user-attachments/files/18016975/val1.csv)
